### PR TITLE
feat: Added new proxy example

### PR DESCRIPTION
**Pull request by Sunderw3k**
Decided to add another example which is a little more advanced.

It shows how you can send the packets and drop some of them.

### CODE REVIEW

**Comment by Sunderw3k** [comment]
oops i think i fricked up the indention

**Comment by Sunderw3k** [comment]
I hope that's good enough. The blank lines are there so the comments are a little more separated from the actual code

if not lmk on what should I do with the comments

**Comment by rom1504** [comment]
failed CI

**Comment by Sunderw3k** [comment]
Uhh so I tried to update the branch and somehow moved all the commits lol. eitherway fixed the checks

**Comment by rom1504** [comment]
idk

**Pull request closed without merging**
